package studio.modroll.critfall.tools;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.resources.ResourceLocation;
import studio.modroll.critfall.combat.Derivation;

/**
 * Pure datapack scaffolder for {@code /critfall generate} (PLAN §8.2.1): given the vanilla stats a
 * pack dev's entities and weapons already expose, it produces a complete, editable set of derived
 * entity/item profiles. No registry access or file IO here — the command layer collects the stats
 * and writes the returned {@code path → json} map to disk, so this stays JVM-testable.
 */
public final class DatapackGenerator {

    /** Datapack namespace for the generated pack — distinct from the shipped {@code critfall} pack. */
    public static final String NAMESPACE = "critfall_generated";

    private static final String COMMENT =
            "regenerated by /critfall generate — edits here are overwritten; copy elsewhere to customize";

    /** 1.21.1 data-pack format. */
    private static final int PACK_FORMAT = 48;

    private static final Gson PRETTY =
            new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    /** The vanilla attribute values a living entity type exposes, before any derivation. */
    public record EntityStat(ResourceLocation id, double armor, double toughness, double attackDamage) {}

    /** The main-hand attack damage a weapon-like item contributes, before any derivation. */
    public record ItemStat(ResourceLocation id, double attackDamage) {}

    private DatapackGenerator() {}

    /** {@code namespace:path} → a unique, filesystem-safe file name (path separators flattened). */
    public static String fileName(ResourceLocation id) {
        return id.getNamespace() + "_" + id.getPath().replace('/', '_') + ".json";
    }

    /** The {@code pack.mcmeta} content for the generated pack. */
    public static String packMcmeta() {
        JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", PACK_FORMAT);
        pack.addProperty("description", "Critfall generated profiles — " + COMMENT);
        JsonObject root = new JsonObject();
        root.add("pack", pack);
        return PRETTY.toJson(root);
    }

    /**
     * Builds one derived {@code entity_profile} per entity and one {@code item_profile} per item.
     * Keys are pack-root-relative paths (e.g. {@code data/critfall_generated/critfall/…}); insertion
     * order follows the input lists.
     */
    public static Map<String, String> generate(List<EntityStat> entities, List<ItemStat> items) {
        Map<String, String> files = new LinkedHashMap<>();
        // The lenient profile parser warns on unknown keys, so the "edits are overwritten" notice
        // lives in pack.mcmeta and this README rather than a per-file _comment key.
        files.put("README.txt", COMMENT + System.lineSeparator());
        for (EntityStat e : entities) {
            JsonObject json = new JsonObject();
            json.add("matches", singletonMatch(e.id()));
            json.addProperty("armor_class", Derivation.armorClass(e.armor(), e.toughness()));
            json.addProperty("attack_bonus", Derivation.attackBonus(e.attackDamage()));
            JsonObject damage = new JsonObject();
            damage.addProperty("melee", Derivation.damageDice(e.attackDamage()).toString());
            json.add("damage", damage);
            json.addProperty("crit_range", 20);
            json.addProperty("priority", 0);
            files.put("data/" + NAMESPACE + "/critfall/entity_profile/" + fileName(e.id()), PRETTY.toJson(json));
        }
        for (ItemStat i : items) {
            JsonObject json = new JsonObject();
            json.add("matches", singletonMatch(i.id()));
            json.addProperty("damage", Derivation.damageDice(i.attackDamage()).toString());
            json.addProperty("modifier_from", "attack_damage_attribute");
            json.addProperty("crit_range", 20);
            json.addProperty("priority", 0);
            files.put("data/" + NAMESPACE + "/critfall/item_profile/" + fileName(i.id()), PRETTY.toJson(json));
        }
        return files;
    }

    private static JsonArray singletonMatch(ResourceLocation id) {
        JsonArray matches = new JsonArray();
        matches.add(id.toString());
        return matches;
    }
}
